### ISSUE TITLE
Incorrect answer on the review question #2

### ISSUE THREAD

**Issue by alexumanamonge** [MicrosoftLearning/AZ-303-Microsoft-Azure-Architect-Technologies#100]
# Module: 10
#### Step: N/A

Description of issue

Repro steps:

1. Choose option 2: "From the Azure portal, modify the value of the Identity option for Tailwind_VM_1.", this marks the answer as incorrect...

2. Choose option 3: "From the Azure portal, modify the Policies settings for Tailwind_RG_1.", it marks the answer as correct... but making reference to the option 2...
![Option3](https://user-images.githubusercontent.com/68295828/123707835-97fa0080-d827-11eb-91fb-bab42fa7173e.png)
![Option2](https://user-images.githubusercontent.com/68295828/123707845-9cbeb480-d827-11eb-9a35-fc912a336d23.png)

**Comment by staleycyn** [comment]
An AZ-303 update is not planned. I will log a bug but there are no plans for releasing a change.
