### ISSUE TITLE
Latest NSG restrictions (lab 5) change causes issues

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-303-Microsoft-Azure-Architect-Technologies#109]
# Latest NSG restrictions (lab 5) change causes issues

Ex 1 Task 2 Step 18: May get "Failed to connect" error. Each Cloud Shell session may have a separate IP address. When you close and re-open Cloud Shell you may get a new IP address for that session. However, when deploying custom-allow-rdp rule in the az30305a-web-nsg we used the IP address from the first Cloud Shell session. Now you are in a second Cloud Shell session. You can update the custom-allow-rdp rule in the az30305a-web-nsg to the new IP address or (better) change the Source option to Any.

**Comment by polichtm** [comment]
updated
