### ISSUE TITLE
Only labs for 5 modules?

### ISSUE THREAD

**Issue by tiagocostapt** [MicrosoftLearning/AZ-303-Microsoft-Azure-Architect-Technologies#12]
Hi AZ-303 development team,

In the official course we have 15 modules but only labs for 5 modules. Is this the expected outcome? 

Best Regards,
Tiago Costa

**Comment by shanecribbs** [comment]
Yes, that is the current state.  6 labs over 5 modules.

**Comment by tiagocostapt** [comment]
@shanecribbs are you  working at the Microsoft Learning Azure Arch team? Really wanted to send some feedback about this. 
@bradjoseph can we have more labs for the other modules. I teach this regularly and really don't think that only this labs would be enough for students to be ready for the exam or for the real world.

**Comment by shanecribbs** [comment]
I work with a different team but help provide internal feedback.  The MCT Courseware Forum might be a better place to make generic overall structure suggestions.  This is a new course and things will mature over time.  Thanks!
https://www.microsoft.com/en-us/learning/mct-courseware-forum.aspx

**Comment by bradjoseph** [comment]
Hi Tiago,

Hope things are well with you. 

As Shane suggests, it would be good to get your feedback (labs) captured in the MCT Courseware Forum. Perhaps we can discuss further with Merrick. 

Thanks,
Brad

**Comment by ElaMark** [comment]
No! definitely no more labs please. I'm running the course this week and it fits nicely into 5 days, 9am to 5pm. I've worked as an MCT for around 25 years, trying to stuff too much material into a week is not good for effective training.

**Comment by polichtm** [comment]
Appreciate the feedback. We'll be closing this issue - if needed, pls follow up via the channels referenced above
rgds
Marcin

**Comment by ElaMark** [comment]
Amendment. On the final day I had students do a [lab on AKS](https://github.com/ElaMark/AZ-301-MicrosoftAzureArchitectDesign/blob/master/Instructions/AZ-301T03_Lab_Mod02_Deploying%20Managed%20Containerized%20Workloads%20to%20Azure.md) and shortened version of [CosmosDB](https://github.com/ElaMark/AZ-301-MicrosoftAzureArchitectDesign/blob/master/Instructions/AZ-301T02_Lab_Mod02_Deploying%20Database%20Instances%20in%20Azure.md)
