### ISSUE TITLE
Lab 7 - used names

### ISSUE THREAD

**Issue by athelen20** [MicrosoftLearning/AZ-303-Microsoft-Azure-Architect-Technologies#16]
# Module: 7
## Lab: 7
Exercise 0
#### Step: 5 and 8

Step 5 calles for the creation of Resource Group az30307a-labRG
Step 8 then uses Resource Group az30308a-labRG
and starting in Task 2 Step 1 it uses Resources labeled az30307a* that were before named with *8*.

Please, rename the resources in Exercise 0 Task 1 Step 8 to *7a*

**Comment by polichtm** [comment]
updated
rgds
Marcin
