### ISSUE TITLE
Mod 01 Exercise 3 Storage Account Type not found

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/AZ-303-Microsoft-Azure-Architect-Technologies#2]
# Module: 01
#### Step: 00

Description of issue
Deployment template validation failed: 'The template variable 'storageAccountType' is not found. Please see https://aka.ms/arm-template/#variables for usage details.'. (Code: InvalidTemplate)

Repro steps:
![image](https://user-images.githubusercontent.com/10166617/84926001-09f32200-b0cb-11ea-97c2-09e4aa20d53c.png)

1.
1.
1.

**Comment by molenaar** [comment]
Using  azuredeploy30301rgc.json and @azuredeploy30301rgc.parameters.json parameter file....

>

**Comment by molenaar** [comment]
![image](https://user-images.githubusercontent.com/10166617/84933433-2ba5d680-b0d6-11ea-91b5-395374cbb371.png)

Must add a storageAccountType variable to the json file.

**Comment by polichtm** [comment]
updated
