### ISSUE TITLE
Module 2, Configure High Availability - not all zones in a region should have the same name "Zone 1"

### ISSUE THREAD

**Issue by christiannagel** [MicrosoftLearning/AZ-303-Microsoft-Azure-Architect-Technologies#21]
# Module: 2
### Availability Zones

In the page and slide *Availability Zone*, one region is shown with three zones named *Zone 1*, *Zone 1*, *Zone 1*. 

They should be named *Zone 1*, *Zone 2*, and *Zone 3*

**Comment by polichtm** [comment]
Hi Christian,
Are you referring to the lab or the content?
In case of the former, which specific lab, exercise, task, and step?
rgds
Marcin

**Comment by polichtm** [comment]
closing due to lack of response

**Comment by christiannagel** [comment]
I'm referring to content - in the slides and in the Skillpipe course materials:
Module 2, Implement VMs for Windows and Linux
Section: Configure High Availability
Subsection: Availability Zones

**Comment by shanecribbs** [comment]
That issue has also been identified through internal channels and will be addressed.  Thanks!
