### ISSUE TITLE
Lab 01 Table/dual-column in a line

### ISSUE THREAD

**Issue by athelen20** [MicrosoftLearning/AZ-303-Microsoft-Azure-Architect-Technologies#22]
# Module: 04
#### Step: 14

Description of issue

There seems to be a table or dual-column in the line which makes it difficult to read.

Repro steps:
Delete the table/dual-column to make it a single coherent line

**Comment by polichtm** [comment]
Here is the step 14:

On the az30301a-lb blade, select the Load balancing rules entry and, on the az30301a-lb | Load balancing rules blade, select the az303001a-lbruletcp80 entry representing the load balancing rule handling HTTP traffic.

Can you clarify what specifically is the issue you are referring to?
rgds
Marcin

**Comment by polichtm** [comment]
closing due to lack of response
