### ISSUE TITLE
Module 4 Lab - Exercise 1 is redundant with Exercise 2

### ISSUE THREAD

**Issue by markturpinMSFT** [MicrosoftLearning/AZ-303-Microsoft-Azure-Architect-Technologies#26]
# Module: 04
#### Step: 00

Description of issue

Exercise 2 consists of the same steps as exercise 1, plus a web request.  What is the value in doing exercise 1?  Why not just lead with exercise 2?  It will reduce deployment time to remove the first exercise.

**Comment by polichtm** [comment]
Hi Mark,
exercise 1 of module 4 covers the following:
Exercise 1: Implement and analyze highly available Azure VM deployments using availability sets and Azure Load Balancer Basic
exercise 2 of module 4 covers the following:
Exercise 2: Implement and analyze highly available Azure VM deployments using availability zones and Azure Load Balancer Standard
They represent two different set of components and design considerations.
rgds
Marcin
