### ISSUE TITLE
Lab 5/Exercise 1/Task 3/Step 4

### ISSUE THREAD

**Issue by azharkhuwaja** [MicrosoftLearning/AZ-303-Microsoft-Azure-Architect-Technologies#29]
Lab 5
Exercise 1
Task 3
Step 4

Second row in table needs to be modified:
"Allowed Service Types"

Modified entry should be:
"Allowed **Resource** Types"

![image](https://user-images.githubusercontent.com/49203962/90107958-0d212c00-dd63-11ea-9874-76b6c1e7fa74.png)

**Comment by azharkhuwaja** [comment]
Same correction also needed in:

Lab 5
Exercise 1
Task 5
Step 1

**Comment by shanecribbs** [comment]
Since you're correcting, the values should be "Service and Container".  Note Service is not plural in the interface.

**Comment by polichtm** [comment]
updated
