### ISSUE TITLE
Module 12, Lab A Typo in Instructions

### ISSUE THREAD

**Issue by markturpinMSFT** [MicrosoftLearning/AZ-303-Microsoft-Azure-Architect-Technologies#30]
# Module: 12
#### Step: 02

Description of issue
In the Azure portal, on the blade displaying the App Service web app deployment slots, **in the row displaying the production slot**, set the value in the TRAFFIC % column to 50. This will automatically set the value of TRAFFIC % in the row representing the production slot to 50.

This should say, "in the row displaying the **staging** slot, set the value in the TRAFFIC % column to 50."

You can't change the traffic for the Production slot.

**Comment by polichtm** [comment]
updated
