### ISSUE TITLE
Module 9/Exercise 2/Task 1/ Step 2

### ISSUE THREAD

**Issue by azharkhuwaja** [MicrosoftLearning/AZ-303-Microsoft-Azure-Architect-Technologies#31]
Module 9
Exercise 2
Task 1
Step 2 and 8

Issue: "Both virtual networks **az30307c-dr-vnet** and **az30307c-test-vnet** have been assigned the same IP address range which is 10.7.0.0/16".

This is not possible. Please change IP address of one of the above virtual networks.

**Comment by shanecribbs** [comment]
I'm pretty sure this is done intentionally as your test recovery network is supposed to use the same IP ranges as your production network.

**Comment by polichtm** [comment]
Would you mind clarifying what you mean by "This is not possible"?
rgds
Marcin

**Comment by azharkhuwaja** [comment]
well, i tried to create virtual network/subnet using same IP address range which was allocated previously to another virtual network/subnet, I got the error. thanks

**Comment by polichtm** [comment]
What was the error? Pls provide the screenshots/steps to reproduce it.
rgds
Marcin

**Comment by azharkhuwaja** [comment]
Issue resolved. Many thanks
