### ISSUE TITLE
Module 12/Lab 12a/Exercise 2/Task 4

### ISSUE THREAD

**Issue by azharkhuwaja** [MicrosoftLearning/AZ-303-Microsoft-Azure-Architect-Technologies#32]
# Module: 12
## Lab/Demo: 12a
Exercise: 2
### Task: 4

Need instructions to remove the directory created for this lab **az30305a1**.
This directory (az30305a1) was created at the beggining of this lab for importing contents from git.

**Comment by polichtm** [comment]
updated
