### ISSUE TITLE
Lab 12a/Exercise 1/Task 2/Step 6

### ISSUE THREAD

**Issue by azharkhuwaja** [MicrosoftLearning/AZ-303-Microsoft-Azure-Architect-Technologies#33]
# Module: 12
## Lab: 12b
Exercise: 1
#### Step: 06

Following line needs to be corrected:
"6. On the Azure Function app blade, select Monitor entry in the Developer section."

Corrected line should be:
"6. On the Azure **Function app** blade, select **Monitor** entry."

This is because there is no Developer section as you can see in screenshot.

![image](https://user-images.githubusercontent.com/49203962/90624780-f2065e80-e231-11ea-962b-73a7de0f6eb7.png)

**Comment by polichtm** [comment]
updated
