### ISSUE TITLE
Update steps for clarity

### ISSUE THREAD

**Issue by shanecribbs** [MicrosoftLearning/AZ-303-Microsoft-Azure-Architect-Technologies#34]
# Module: 07
#### Step: 5

Not clear on which window/account to use progressing into Task3, although it is critical.  I'd recommend adding a step at the end of Task 2 to close the InPrivate window AND/OR be clear in the beginning of Task 3 to use your Service Administrator account and not the new testing account.

**Comment by polichtm** [comment]
updated
