### ISSUE TITLE
Module9_lab instructions drift task 2 line 310

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/AZ-303-Microsoft-Azure-Architect-Technologies#39]
# Module: 9
#### Step: 02

Description of issue Need to change "For on-premises machines " to "Hyper-V" on line 310

#### Task 2: Implement protection of a Hyper-V virtual machine

1. Within the Remote Desktop session to **az30307a-hv-vm**, in the Azure portal, on the **az30307b-rsvault** blade, in the **Getting started** section, select **Site Recovery**
1. On the **az30307b-rsvault | Site Recovery** blade, in the **For on-premises machines** section, select **Prepare infrastructure**. 

Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
Hi David,
would you mind clarifying what specifically you're referring to?
Here is the current content of this module you are referencing:

Task 2: Implement protection of a Hyper-V virtual machine
1. Within the Remote Desktop session to az30307a-hv-vm, in the Azure portal, on the az30307b-rsvault blade, in the Getting started section, select Site Recovery
1. On the az30307b-rsvault | Site Recovery blade, in the Hyper-V machines to Azure section, select 1. Prepare infrastructure.

rgds
Marcin

**Comment by dpapkin** [comment]
In Exercise 2 , Task2
1. On the **az30307b-rsvault | Site Recovery** blade, in the **For on-premises machines** section, select **Prepare infrastructure**. 

As you can see in my screenshot, there is no "For on-premises machines" choice, there is only  "Azure","VMwar"e or "Hyper-V" . 

I assume the correct choice is now Hyper-V machines, which makes sense with the lab flow

![image](https://user-images.githubusercontent.com/24426530/93693023-f2de2900-fb2c-11ea-96a9-65943bbd6d76.png)

**Comment by polichtm** [comment]
Hi David,
it appears that you are missing my point. Here is the content you are referring to in the CURRENT version in THIS  repo:

https://github.com/MicrosoftLearning/AZ-303-Microsoft-Azure-Architect-Technologies/blob/master/Instructions/Labs/Module_9_Lab.md

What specifically do you want to change? This obviously does not match the content you are referring to...
rgds
Marcin

**Comment by dpapkin** [comment]
Hi,

You are correct. It has been updated.

Thank you
