### ISSUE TITLE
MODULE 9, EXERCISE 2, TASK 2, STEP 29 - ERROR?

### ISSUE THREAD

**Issue by dalleeson** [MicrosoftLearning/AZ-303-Microsoft-Azure-Architect-Technologies#40]
# Module: 09
#### Step: 29

Description of issue
regarding the labs for MODULE 9, EXERCISE 2, TASK 2, STEP 29. Its wants you to select a Resource Group called az30307b-rg3, but this does not exist and I cannot find any reference to create this group in earlier steps?

I have raised this in the Team Channel for trainers, it was suggested to report it here. Can you please fix / advise the correct steps?

Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
updated
rgds
Marcin

**Comment by dalleeson** [comment]
Thank you!!
