### ISSUE TITLE
Lab 04 Exercise 2 Task 2 Step 23; UI Change; Command Line Replacement

### ISSUE THREAD

**Issue by bakirnajjar** [MicrosoftLearning/AZ-303-Microsoft-Azure-Architect-Technologies#44]
# Module: 04
## Lab/Demo: 04
###Exercise 2
##### Step: 23

Description of issue
In Lab 04 Exercise 2 Task 2 Step 23,

On the az30301b-lb blade, select the Load balancing rules entry and, on the az30301b-lb | Load balancing rules blade, select the az303001b-lbruletcp80 entry representing the load balancing rule handling HTTP traffic.

It seems that there is change in the UI, so here the command line to do it by CLI: 
az network lb rule update -g az30301b-labRG --lb-name az30301b-lb -n az303001b-lbruletcp80 --disable-outbound-snat true

**Comment by massimobonanni** [comment]
Hi, I think you can use the last option in the blade as shown in the follow image

![image](https://user-images.githubusercontent.com/9560142/95308103-be3ad300-0889-11eb-8126-ef0170b54bb8.png)

**Comment by polichtm** [comment]
updated
rgds
Marcin
