### ISSUE TITLE
Lab 9 - Exercise 2 - Task 2 - Step 29 - Post-failover Azure network doesn't exist 

### ISSUE THREAD

**Issue by massimobonanni** [MicrosoftLearning/AZ-303-Microsoft-Azure-Architect-Technologies#46]
# Module: 09
#### Step: 29

Description of issue
The vnet called `az30307b-dr-vnet` doesn't exist and the students need to choose the network from a combo. Is it the right vnet the `az30307c-dr-vnet`?

**Comment by polichtm** [comment]
updated
