### ISSUE TITLE
Update AllFiles folder names

### ISSUE THREAD

**Issue by shanecribbs** [MicrosoftLearning/AZ-303-Microsoft-Azure-Architect-Technologies#49]
The folder names in the AllFiles download don't match the module numbers.  Can we update AllFiles and the lab instructions to reference the correct module number or come up with some arbitrary naming convention to avoid confusion?

**Comment by polichtm** [comment]
Hi Shane,
that's a valid point. An update is in the works...
rgds
Marcin

**Comment by polichtm** [comment]
completed
