### ISSUE TITLE
Network Watcher not enabled on subscription

### ISSUE THREAD

**Issue by derekoharrow** [MicrosoftLearning/AZ-303-Microsoft-Azure-Architect-Technologies#55]
# Module: AZ-303
#### Step: 02

The lab instructions say to enable Network Watcher for the resource group az30305a-labRG, but this doesn't appear in the selection box for Network Watcher and Network Watcher isn't enabled for the subscription as part of the instructions.

I had to go into the Network Watcher overview and turn-on Network Watcher for the subscription, and then wait for this to take effect before I could enable Network Watcher.

**Comment by polichtm** [comment]
Hi Derek,
Network Watcher should be automatically enabled in the regions where you created virtual networks (which is part of the preceding exercise). Can you clarify what you mean by "turn-on Network Watcher for the subscription"?
rgds
Marcin

**Comment by polichtm** [comment]
closing due to lack of response
