### ISSUE TITLE
issue - AZ-303-Microsoft-Azure-Architect-Technologies/Instructions/Labs/Module_12_Lab.md

### ISSUE THREAD

**Issue by mjnasir786** [MicrosoftLearning/AZ-303-Microsoft-Azure-Architect-Technologies#58]
# Module: 12lab
#### Step: 05
AZ-303-Microsoft-Azure-Architect-Technologies/Instructions/Labs/Module_12_Lab.md

**Description of issue**
I am new to power shell, sorry for my lack of knowledge in this area.
I could not run the following on the power shell window as stated in task 1 step 5

$location = 'uk south'
New-AzSubscriptionDeployment `
  -Location $location `
  -Name az30312subaDeployment `
  -TemplateFile $HOME/azuredeploy30312suba.json `
  -rgLocation $location `
  -rgName 'az30312a-labRG'

I get the following error:

PS /home/mohammad> $location = 'uk south' New-AzSubscriptionDeployment -Location $location -Name az30312subaDeployment -TemplateFile $HOME/azuredeploy30312suba.json -rgLocation $location -rgName 'az30312a-labRG'
ParserError:
Line |
   1 |  $location = 'uk south' New-AzSubscriptionDeployment -Location $locati …
     |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Unexpected token 'New-AzSubscriptionDeployment' in expression or statement.

Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
It appears that you included the New-AzSubscriptionDeployment cmdlet as part of the same line that assigns the value to the $location variable. These should be two separate lines.
Btw. pls note that this forum is intended for MCTs. If you have any questions regarding the course labs, you should refer to your instructor.
rgds
Marcin

**Comment by mjnasir786** [comment]
Sorry Marcin, 
I am new to GITHUB, as I was stuck on this command mentioned in the Lab in GITHUB, I thought this forum is open for all, what is MCT?
Since you were so kind to help/ reply, could you also help with the correct command? are you saying that there should be a "-" before  **New-AzSubscriptionDeployment -Location $location**, I mean like below?

$location = 'uk south'
-New-AzSubscriptionDeployment -Location $location
-Name az30312subaDeployment -TemplateFile $HOME/azuredeploy30312suba.json
-rgLocation $location `
-rgName 'az30312a-labRG'
