### ISSUE TITLE
Task number and hostname error in AZ-303 Lab-12

### ISSUE THREAD

**Issue by ervee** [MicrosoftLearning/AZ-303-Microsoft-Azure-Architect-Technologies#66]
# Module: AZ-303
#### Step: 1

First: Exercise 2, Task 4 is specified twice! The ```Remove Azure resources deployed in the lab``` task should be task 5.

In both Exercise 2 task 4 and 5, ```az30312a-vm0``` should be ```az30312a-hv-vm```.

**Comment by polichtm** [comment]
updated
rgds
Marcin
