### ISSUE TITLE
Missing extension

### ISSUE THREAD

**Issue by TechGuyVincent** [MicrosoftLearning/AZ-303-Microsoft-Azure-Architect-Technologies#68]
# Module: 00
#### Step: 08

Missing the network watcher extension required to make step 8 work. Recommend that you add the extension in the RCA JSON file. After installing it, it works (could not select any VMs before installing the extension manually). 

Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
Hi Vincent,

as per the Note following step 8:

"Note: You will need to wait a few minutes for the results in order for the Azure Network Watcher Agent VM extension to be installed on the Azure VMs."

Unfortunately I cannot reproduce the behavior you are describing - I can select any virtual machine in the Connection troubleshoot interface - regardless of whether they have the extension installed. 

Would you mind posting the screenshots illustrating what you're referring to?

rgds
Marcin

**Comment by polichtm** [comment]
closing due to lack of response
