### ISSUE TITLE
Display list of regions to which to select

### ISSUE THREAD

**Issue by shanecribbs** [MicrosoftLearning/AZ-303-Microsoft-Azure-Architect-Technologies#70]
# Module: 05
#### Step: 06

Description of issue
We ask users to enter a region name without giving the exact formatting.  Could we insert a step to display the available regions before having them set the LOCATION variable?

az account list-locations --query "[].{name:name}" -o table

This would be easier in PowerShell, but sticking with bash since that is what they have entered already.

Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
Hi Shane, 
as per instructions:

updated
rgds
Marcin
