### ISSUE TITLE
Pre-Register Network Watcher

### ISSUE THREAD

**Issue by shanecribbs** [MicrosoftLearning/AZ-303-Microsoft-Azure-Architect-Technologies#71]
# Module: 05
#### Step: 06

Description of issue
We are getting a relatively high rate of students where Network Watcher doesn't automatically enable quickly enough or at all.  Can we add a step in Task 1, just after defining the LOCATION variable, to pre-register the Network Watcher to be ready for Task 2?

az network watcher configure --resource-group NetworkWatcherRG --locations $LOCATION --enabled -o table

Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
Hi Shane
updated
rgds
Marcin
