### ISSUE TITLE
VMSS autoscale not triggering

### ISSUE THREAD

**Issue by shanecribbs** [MicrosoftLearning/AZ-303-Microsoft-Azure-Architect-Technologies#72]
# Module: 05
#### Step: 5 and 7

Description of issue
The default rules seem a bit too high and autoscaling doesn't trigger for all attendees.  Perhaps we could change the default setting of CPU threshold (75%) down to 40% or 50%?

Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
Hi Shane, 
Could you clarify which setting you are referring to? As per instructions:

![image](https://user-images.githubusercontent.com/10284906/110172720-906fa100-7dcb-11eb-8071-4097fda27a6a.png)


rgds
Marcin

**Comment by shanecribbs** [comment]
There is a setting called "CPU threshold" not mentioned in the table because we leave it at the default value of 75%.

**Comment by polichtm** [comment]
Hi Shane,
would you mind providing a screenshot of what you're referring to?
Here is what I'm seeing:

![image](https://user-images.githubusercontent.com/10284906/110175853-68367100-7dd0-11eb-93f0-5e344b491395.png)

rgds
Marcin

**Comment by polichtm** [comment]
Closing due to lack of response
