### ISSUE TITLE
New version of Azure Storage Explorer breaks lab

### ISSUE THREAD

**Issue by shanecribbs** [MicrosoftLearning/AZ-303-Microsoft-Azure-Architect-Technologies#73]
# Module: 06
#### Step: 00

The new version of Azure Storage Explorer (1.18) has a different UI and doesn't allow using the same SAS connection URI options.  Tasks 3 and 4 need to be updated, as well as any other steps that may leverage Azure Storage Explorer.

Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
updated
rgds
Marcin
