### ISSUE TITLE
Module 14 b/Exercise 1/task 1/ Step 11

### ISSUE THREAD

**Issue by azharkhuwaja** [MicrosoftLearning/AZ-303-Microsoft-Azure-Architect-Technologies#74]
# Module: 14 b
#### Step: 11

following script is incorrect:
--------------------------
11. From the Cloud Shell pane, run the following to create the Azure Function that will process events corresponding to creation of Azure Storage blobs:

export FUNCTION_NAME="az303**09**f${PREFIX}"
---------------------------------

It should be changed to:

export FUNCTION_NAME="az30314f${PREFIX}"

**Comment by polichtm** [comment]
updated
rgds
Marcin
