### ISSUE TITLE
Module 6/Exercise 3/Task 2/Step 4

### ISSUE THREAD

**Issue by azharkhuwaja** [MicrosoftLearning/AZ-303-Microsoft-Azure-Architect-Technologies#76]
# Module: 06
#### Step: 4

Description of issue
when I paste powershell script for "connect" into cloudshell (powershell), I get two errors.
1. Test-NetConnection is not recognized.
2.  Port 445 is blocked.

How to fix both issues, thanks. Screenshot is attached.
![Untitled](https://user-images.githubusercontent.com/49203962/111612766-a0da3f80-87ff-11eb-8c61-30ba7e6847a2.png)

**Comment by renaudwangler** [comment]
The script needs to be pasted in the remote VM Powershell, not in the cloudShell ;)

**Comment by azharkhuwaja** [comment]
thank you.
