### ISSUE TITLE
Module 6/ Exercise 2/Task 3/Step 5

### ISSUE THREAD

**Issue by azharkhuwaja** [MicrosoftLearning/AZ-303-Microsoft-Azure-Architect-Technologies#77]
# Module: 06
#### Step: 05

Description of issue

Following command doesn't work.

>.\azcopy.exe login

solution: command should be
>azcopy login

screenshot attached. thanks
![Untitled](https://user-images.githubusercontent.com/49203962/111614370-55289580-8801-11eb-9de9-25400a96269e.png)

**Comment by renaudwangler** [comment]
Hi!
This task has to be done in the reote vm powershell, not in the cloudShell ;)

**Comment by azharkhuwaja** [comment]
thank you.
