### ISSUE TITLE
Module 6/exercise 2/task 3/steps 1 and 2

### ISSUE THREAD

**Issue by azharkhuwaja** [MicrosoftLearning/AZ-303-Microsoft-Azure-Architect-Technologies#78]
# Module: 06
#### Step: 1 and 2

Description of issue
steps 1 and 2 are redundant as same action is repeated in step 4 using PowerShell. Steps 1 and 2 should be deleted as I tried to do the same using portal (steps 1 and 2) and later using powershell (step 4). thanks

**Comment by polichtm** [comment]
updated
rgds
Marcin
