### ISSUE TITLE
Module 06 - Unable to install Microsoft Edge

### ISSUE THREAD

**Issue by nicolastson1** [MicrosoftLearning/AZ-303-Microsoft-Azure-Architect-Technologies#87]
# Module: 06
#### Step: Within the Remote Desktop session to az30306a-vm0, start Internet Explorer, navigate to the download page of Microsoft Edge, download Microsoft Edge installer and perform the installation.

Description of issue:
I tried installing Microsoft Edge from Internet Explorer, but I keep getting two pop-ups. The first pop-up says: "Do you want to allow this website to open an app on your computer?" I click the "Allow button" and it brings up the the second pop-up. It says: "You'll need a new app to open this Microsoft-edge." 

Repro steps:
1. I reset Internet explorer settings in the "Internet options"
1. Set my "Change User Account Control settings" to "Never notify me when..."

Can anyone please tell me how to fix this in order to get to the next steps of the lab?

**Comment by polichtm** [comment]
You'd need to use https://www.microsoft.com/en-us/edge/business/download
Btw. pls note that this repo is intended for MCTs...
rgds
Marcin
