### ISSUE TITLE
Module 12 - Azure Quickstart template url is invalid

### ISSUE THREAD

**Issue by tohov** [MicrosoftLearning/AZ-303-Microsoft-Azure-Architect-Technologies#88]
# Module: 12
#### Step: 07

Description of issue
Azure Quickstart Template link results in 404 error. The template does not seem to exist anymore. ([301-nested-vms-in-virtual-network](https://github.com/Azure/azure-quickstart-templates/tree/master/301-nested-vms-in-virtual-network))

Repro steps:

1. Try opening the link provided in the description or in the lab steps (or [here](https://github.com/Azure/azure-quickstart-templates/tree/master/301-nested-vms-in-virtual-network))

**Comment by massimobonanni** [comment]
The template was moved from the original folder to https://github.com/Azure/azure-quickstart-templates/tree/master/demos/nested-vms-in-virtual-network

**Comment by laudibert** [comment]
The new link is: https://github.com/Azure/azure-quickstart-templates/tree/master/demos/nested-vms-in-virtual-network

**Comment by polichtm** [comment]
addressed by #90
