### ISSUE TITLE
Change VM in templates?

### ISSUE THREAD

**Issue by ConcreteGannet** [MicrosoftLearning/AZ-303-Microsoft-Azure-Architect-Technologies#93]
Several labs use Standard_D2s_v3 VMs. When you try to deploy to the Australia East region, these bring on a "not available" error, even though the portal says they should be possible (https://azure.microsoft.com/en-us/global-infrastructure/services/?products=virtual-machines&regions=australia-central,australia-east,australia-southeast).

Is anyone else seeing this? Should the templates be changed to a v4 VM, such as Standard_D2as_v4?

**Comment by ConcreteGannet** [comment]
https://github.com/MicrosoftLearning/AZ-303-Microsoft-Azure-Architect-Technologies/blob/e3737018dc90c3f37728835ce7620c75cc30648b/Allfiles/Labs/05/azuredeploy30305rga.json#L49
https://github.com/MicrosoftLearning/AZ-303-Microsoft-Azure-Architect-Technologies/blob/e3737018dc90c3f37728835ce7620c75cc30648b/Allfiles/Labs/05/azuredeploy30305rgb.json#L35
https://github.com/MicrosoftLearning/AZ-303-Microsoft-Azure-Architect-Technologies/blob/e3737018dc90c3f37728835ce7620c75cc30648b/Allfiles/Labs/05/azuredeploy30305rgc.json#L35
https://github.com/MicrosoftLearning/AZ-303-Microsoft-Azure-Architect-Technologies/blob/a38740d127b20bfa14ea4c7826bb901b1a13a5c2/Allfiles/Labs/06/azuredeploy30306rga.json#L33
https://github.com/MicrosoftLearning/AZ-303-Microsoft-Azure-Architect-Technologies/blob/a38740d127b20bfa14ea4c7826bb901b1a13a5c2/Allfiles/Labs/10/azuredeploy30310rga.json#L33

Yes, you can supply a parameter value, but the lab instructions do not say to do that, and the default value has not worked for several weeks now in Australia East. I wonder if they are not allowing any new instances of D series v3 machines in Australia East but have not documented that yet.

**Comment by polichtm** [comment]
updated
rgds
Marcin
